apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^logout$', views.logout, name='logout'),
	url(r'^login$', views.login, name='login'),
	url(r'^register$', views.register, name='register'),
]

black_belt_exam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.blackbelt.urls', namespace='main')),
    url(r'^main/', include('apps.login.urls', namespace='login')),
    url(r'^travels/', include('apps.travels.urls', namespace='travel')),

]

apps/login/models.py
from __future__ import unicode_literals
import re
import bcrypt
from django.db import models

NAME_REGEX = re.compile(r'^[a-zA-Z]{3,}$')
PASSWORD_REGEX = re.compile(r'^[a-zA-Z0-9.#!?$\+=*]{8,255}')

# Create your models here.
class UserManager(models.Manager):
	"""docstring for UserManager."""
	def login(self, **kwargs):
		errors = []
		username = str(kwargs['username'][0])
		password = str(kwargs['password'][0])
		incorrect = False

		if not NAME_REGEX.match(username):
			incorrect = True
			errors.append('Please insert a valid username.')
		if not PASSWORD_REGEX.match(password):
			incorrect = True
			errors.append('Please insert a valid password.')

		if incorrect:
			return (False, errors)

		try:
			user = User.objects.get(username=username)
		except Exception as e:
			errors.append("I'm sorry, the entered username does not exist.")
			return (False, errors)

		if user.password != bcrypt.hashpw(password, user.password.encode()):
			errors.append('I\'m sorry, the password you entered was wrong.')
			return (False, errors)

		return (True, 'Successful Login', {'id': user.id, 'name' : user.name})




	def register(self, **kwargs):
		errors = []
		username = str(kwargs['username'][0])
		name = str(kwargs['name'][0])
		password = str(kwargs['password'][0])
		confirm = str(kwargs['confirmation'][0])
		incorrect = False

		# Name check
		if not NAME_REGEX.match(name):
			incorrect = True
			errors.append("Please enter a name with only characters and is at least 3 characters long.")


		# Username Check
		if not NAME_REGEX.match(username):
			incorrect = True
			errors.append("Please enter a username with only characters and is at least 3 characters long.")

		# Password Checks
		if not PASSWORD_REGEX.match(password):
			incorrect = True
			errors.append("Please enter a password with 8 or more characters and with valid characters\n [Valid characters are: '.' '#' '!' '?' '+' '=' '*'] ")
		elif not password == confirm:
			incorrect = True
			errors.append("Passwords do not match, try again")

		# Check to see if flag was tripped at all
		if incorrect:
			return (False, errors)

		hashed = bcrypt.hashpw(password, bcrypt.gensalt(14))

		try:
			user = User.objects.create(name=name, password=hashed, username=username)
		except Exception as e:
			errors.append("I'm sorry, there is already a user with that username.")
			return (False, errors)

		return (True, 'Successfully registered!', {'id' : user.id, 'name' : name})


class User(models.Model):
	"""docstring for User."""
	name = models.CharField(max_length=90)
	password = models.CharField(max_length=255)
	username = models.CharField(max_length=50, unique=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()

apps/login/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from .models import User

# Create your views here.
def index(request):
	for user in User.objects.all():
		print user.username
	
	# removes = User.objects.all().delete()
	return render(request, 'login/index.html')


def show_edit(request):
	context = {
		'users' : User.objects.all()
	}
	return render(request, 'login/edit.html', context)

def logout(request):
	request.session.flush()
	return redirect(reverse('login:index'))


def login(request):
	response = User.objects.login(**request.POST)
	if not response[0]:
		for message in response[1]:
			messages.error(request, message)
		return redirect(reverse('login:index'))

	messages.success(request, response[1])
	request.session['id'] = response[2]['id']
	request.session['first_name'] = response[2]['name']

	return redirect(reverse('travel:index'))


def register(request):
	response = User.objects.register(**request.POST)
	if not response[0]:
		for message in response[1]:
			messages.error(request, message)
		return redirect(reverse('login:index'))

	messages.success(request, response[1])

	request.session['id'] = response[2]['id']
	request.session['first_name'] = response[2]['name']
	return redirect(reverse('travel:index'))

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Sign Up Or Login</title>
		{% load staticfiles %}
		<link rel="stylesheet" href="{%static 'login/css/materialize.css' %}">
		<link rel="stylesheet" href="{% static 'login/css/style.css' %}">
	</head>
	<body>
		<div id="container">
			<header class="teal-border border-bottom">
				<h1>Trip Tumult!</h1>
			</header>
			<main>
				{% if messages %}
				{% for message in messages %}
				<p class="flash-message red">{{message}}</p>
				{% endfor %}
				{% endif%}
				<div id="session-section">
					{% if 'id' in request.session %}
					<span id="greeting" class="">Welcome, {{request.session.first_name}}</span>
					<a class="session-button" href="{% url 'login:logout' %}">Logout</a>
					{% else %}
					<span id="greeting" class="">Welcome! Please feel free to </span>
					<a href="#login-modal" class="session-button">Login</a>
					<a href="#register-modal" class="session-button">Register</a>
					{% endif %}
				</div>
				<div id="login-modal" class="modal modal-fixed-footer">
					<div class="modal-content">
						<h4 class="teal-text">Login</h4>
						<div class="row">
							<form id="login-form" class="col s12" action="{% url 'login:login' %}" method="post">
								{% csrf_token %}
								<div class="row">
									<div class="input-field col s12">
										<input id="login-username" name="username" type="text">
										<label for="login-username">Username</label>
									</div>
								</div>
								<div class="row">
									<div class="input-field col s12">
										<input id="login-password" name="password" type="password" class="validate">
										<label for="login-password">Password</label>
									</div>
								</div>
							</form>
						</div>
					</div>
					<div class="modal-footer">
						<button form="login-form" type="submit" class="modal-action modal-close waves-effect waves-green btn-flat ">Login</button>
					</div>
				</div>
				<div id="register-modal" class="modal modal-fixed-footer">
					<div class="modal-content">
						<h4 class="teal-text">Register</h4>
						<div class="row">
							<form id="register-form" class="col s12" action="{% url 'login:register' %}" method="post">
								{% csrf_token %}
								<div class="row">
									<div class="input-field col s12">
										<input id="name" name="name" type="text" >
										<label for="name">Name</label>
									</div>
								</div>
								<div class="row">
									<div class="input-field col s12">
										<input id="username" type="text" name="username">
										<label for="username">Username</label>
									</div>
								</div>
								<div class="row">
									<div class="input-field col s6">
										<input id="password" name="password" type="password" >
										<label for="password">Password</label>
									</div>
									<div class="input-field col s6">
										<input id="confirmation" name="confirmation" type="password" >
										<label for="confirmation">Password Confirmation</label>
									</div>
								</div>
							</form>
						</div>
					</div>
					<div class="modal-footer">
						<button form="register-form" formaction="{% url 'login:register' %}" type="submit" class="modal-action modal-close waves-effect waves-green btn-flat ">Register</button>
					</div>
				</div>
			</main>
		</div>
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="{% static 'login/js/materialize.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'login/js/app.js' %}">

		</script>
	</body>
</html>