apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^logout$', views.logout, name='logout'),
	url(r'^login$', views.login, name='login'),
	url(r'^register$', views.register, name='register'),
]

apps/travels/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^add$', views.show_add, name='show_add'),
	url(r'^add/process/(?P<id>\d+)$', views.create, name='create'),
	url(r'^trip/(?P<id>\d+)$', views.show_trip, name='show_trip'),
	url(r'^trip/(?P<id>\d+)/join$', views.join, name='join'),
]

black_belt_exam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.blackbelt.urls', namespace='main')),
    url(r'^main/', include('apps.login.urls', namespace='login')),
    url(r'^travels/', include('apps.travels.urls', namespace='travel')),

]

apps/travels/models.py
from __future__ import unicode_literals
from datetime import datetime
import re
from django.db import models
from ..login.models import User

DESTINATION_REGEX = re.compile(r'^[a-zA-Z\'\". ]{5,}$')

# Create Model Managers
class TripManager(models.Manager):
	"""docstring for TripManager."""
	def validate(self, id, **kwargs):
		incorrect = False
		errors = []
		# Collect error free values from kwargs and validate
		destination = str(kwargs['destination'][0])
		description = str(kwargs['description'][0])

		print incorrect
		# Destination Null check
		if not DESTINATION_REGEX.match(destination):
			incorrect = True
			errors.append('Please enter a destination for your trip.')
		# Description Null check
		if description and len(description) < 10:
			incorrect = True
			errors.append("If you're going to enter a description, make sure that You enter one at least 10 characters long.")

		print incorrect, 'before tries'
		# Collect error prone values from kwargs and validate
		try:
			travel_to = datetime.strptime(str(kwargs['travel_to'][0]), '%d %B, %Y')
		except Exception as e:
			incorrect = True
			errors.append("Please enter a value for 'Travel To'")

		try:
			travel_from = datetime.strptime(str(kwargs['travel_from'][0]), '%d %B, %Y')
		except Exception as e:
			incorrect = True
			errors.append("Please enter a value for 'Travel From'")

		print incorrect, 'before tries'
		try:
			delta = travel_to - travel_from
			if delta.days < 0:
				incorrect = True
				errors.append("The 'Travel To' date must be further in the future than the travel from date.")
		except Exception as e:
			print e

		if incorrect:
			return (False, errors)

		try:
			user = User.objects.get(id=id)
		except Exception as e:
			errors.append("You somehow managed to get to this page without signing in. Go back home and sign in!")
			return (False, errors)

		trip = Trip.objects.create(destination=destination, description=description, owner=user, travel_from=travel_from, travel_to=travel_to)
		User_Trip.objects.create(attendee=user, trip=trip)

		message = 'Created trip to '+ destination + '!'
		return (True, message)


# Create your models here.
class Trip(models.Model):
	"""docstring for Trip."""
	destination = models.CharField(max_length=45)
	description = models.TextField(max_length=1000)
	owner = models.ForeignKey(User)
	travel_from = models.DateTimeField()
	travel_to = models.DateTimeField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = TripManager()


class User_Trip(models.Model):
	"""docstring for User_Trip."""
	attendee = models.ForeignKey(User)
	trip = models.ForeignKey(Trip)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

apps/travels/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from .models import Trip, User_Trip
from ..login.models import User

# Create your views here.
def index(request):
	user_trips = User_Trip.objects.filter(attendee_id=request.session['id'])
	other_trips = Trip.objects.exclude(owner_id=request.session['id'])
	for trip in user_trips:
		other_trips = other_trips.exclude(id=trip.trip.id)

	context = {
		'other_trips': other_trips,
		'user_trips': user_trips
	}

	return render(request, 'travels/index.html', context)


def show_add(request):
	return render(request, 'travels/add.html')


def show_trip(request, id):
	trip = Trip.objects.get(id=id)
	context = {
		'trip_attendees': User_Trip.objects.filter(trip=trip),
		'trip' : trip
	}
	print trip.destination
	print context['trip_attendees']
	return render(request, 'travels/trip.html', context)


def create(request, id):
	response = Trip.objects.validate(id, **request.POST)
	if not response[0]:
		print response[0]
		for message in response[1]:
			messages.error(request, message)
		return redirect(reverse('travel:show_add'))
	else:
		print response[1]
		messages.success(request, response[1])
	return redirect(reverse('travel:index'))

def join(request, id):
	User_Trip.objects.create(attendee=User.objects.get(id=request.session['id']), trip=Trip.objects.get(id=id))
	return redirect(reverse('travel:index'))

apps/travels/templates/travels/add.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Users</title>
		{% load staticfiles %}
		<link rel="stylesheet" href="{%static 'login/css/materialize.css' %}">
		<link rel="stylesheet" href="{% static 'login/css/style.css' %}">
	</head>
	<body>
		<div id="container">
			<header class="teal-border border-bottom">
				<h1>Trip Tumult!</h1>
				<div id="session-section">
					{% if 'id' in request.session %}
					<span id="greeting" class="">Welcome, {{request.session.first_name}}</span>
					<a class="session-button" href="{% url 'travel:index' %}">Home</a>
					<a class="session-button teal-border" href="{% url 'login:logout' %}">Logout</a>
					{% else %}
					<span id="greeting" class="">Welcome! Please feel free to </span>
					<a href="#login-modal" class="session-button teal-border">Login</a>
					<a href="#register-modal" class="session-button teal-border">Register</a>
					{% endif %}
				</div>
			</header>
			<main>
				<h3 class='teal-text'>Add a Trip</h3>
				<div class="row valign-wrapper">
					<form id="trip-form" class="col s6" method="post">
						{% csrf_token %}
						<div class="row">
							<div class="input-field col s12">
								<input id="name" name="destination" type="text" >
								<label for="name">Destination</label>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<input id="username" type="text" name="description">
								<label for="username">Description</label>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s6">
								<input id="travel-from" name="travel_from" type="date" class="datepicker">
								<label for="travel-from">Travel From</label>
							</div>
							<div class="input-field col s6">
								<input id="travel-to" name="travel_to" type="date" class="datepicker">
								<label for="travel-to">Travel To</label>
							</div>
						</div>
						<button type="submit" form='trip-form' formaction="{% url 'travel:create' id=request.session.id %}" class="modal-action modal-close waves-effect waves-green btn-flat teal-text teal-border right">Add Trip</button>
					</form>
					<div class="col s6 valign space-between">
						{% if messages %}
						{% for message in messages %}
						<p class="flash-message {{message.tags}}">{{message}}</p>
						{% endfor %}
						{% endif%}
					</div>
				</div>

			</main>
		</div>
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="{% static 'login/js/materialize.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'login/js/app.js' %}">

		</script>
	</body>
</html>

apps/travels/templates/travels/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Travel Time</title>
		{% load staticfiles %}
		<link rel="stylesheet" href="{%static 'login/css/materialize.css' %}">
		<link rel="stylesheet" href="{% static 'login/css/style.css' %}">
	</head>
	<body>
		<div id="container">
			<header class="teal-border border-bottom">
				<h1>Trip Tumult!</h1>
				<div id="session-section">
					{% if 'id' in request.session %}
					<span id="greeting" class="">Welcome, {{request.session.first_name}}</span>
					<a class="session-button" href="{% url 'travel:index' %}">Home</a>
					<a class="session-button" href="{% url 'login:logout' %}">Logout</a>
					{% else %}
					<span id="greeting" class="">Welcome! Please feel free to </span>
					<a href="#login-modal" class="session-button">Login</a>
					<a href="#register-modal" class="session-button">Register</a>
					{% endif %}
				</div>
			</header>
			<main>
				{% if messages %}
				{% for message in messages %}
				<p class="flash-message green">{{message}}</p>
				{% endfor %}
				{% endif%}
				<h3 class="table-head">Your Trip Schedules</h3>
				<table>
					<thead>
						<tr>
							<th>Destination</th>
							<th>Travel Start Date</th>
							<th>Travel End Date</th>
							<th>Travel Plan</th>
						</tr>
					</thead>
					<tbody>
						{% for trip in user_trips %}
						<tr>
							<td> <a class="route route-destination" href="{% url 'travel:show_trip' id=trip.trip.id %}">{{trip.trip.destination}}</a></td>
							<td>{{trip.trip.travel_from}}</td>
							<td>{{trip.trip.travel_to}}</td>
							<td>{{trip.trip.description}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				<h3 class="table-head">Other Users Travel Plans</h3>
				<table>
					<thead>
						<tr>
							<th>Trip Owner</th>
							<th>Destination</th>
							<th>Travel Start Date</th>
							<th>Travel End Date</th>
							<th>Do You Want to Join?</th>
						</tr>
					</thead>
					<tbody>
						{% for trip in other_trips %}
							<tr>
								<td>{{trip.owner.name}}</td>
								<td> <a class="route route-destination" href="{% url 'travel:show_trip' id=trip.id %}">{{trip.destination}}</a></td>
								<td>{{trip.travel_from}}</td>
								<td>{{trip.travel_to}}</td>
								<td><a href="{% url 'travel:join' id=trip.id %}" class="route-add-trip">Join Trip?</a></td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				<a href="{% url 'travel:show_add' %}" class="route route-add-trip">Add a Trip</a>
			</main>
		</div>
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="{% static 'login/js/materialize.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'login/js/app.js' %}">

		</script>
	</body>
</html>

apps/travels/templates/travels/trip.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Travel Time</title>
		{% load staticfiles %}
		<link rel="stylesheet" href="{%static 'login/css/materialize.css' %}">
		<link rel="stylesheet" href="{% static 'login/css/style.css' %}">
	</head>
	<body>
		<div id="container">
			<header class="teal-border border-bottom">
				<h1>Trip Tumult!</h1>
				<div id="session-section">
					{% if 'id' in request.session %}
					<span id="greeting" class="">Welcome, {{request.session.first_name}}</span>
					<a class="session-button" href="{% url 'travel:index' %}">Home</a>
					<a class="session-button" href="{% url 'login:logout' %}">Logout</a>
					{% else %}
					<span id="greeting" class="">Welcome! Please feel free to </span>
					<a href="#login-modal" class="session-button">Login</a>
					<a href="#register-modal" class="session-button">Register</a>
					{% endif %}
				</div>
			</header>
			<main>
				<section class="trip-page-section trip-info">
					<h3>{{trip.destination}}</h3>
					<div class="data">
						<p>Planned By: {{trip.owner.name}}</p>
						<p>Description:  {{trip.description}}</p>
						<p>Travel Date From: {{trip.travel_from}}</p>
						<p>Travel Date To: {{trip.travel_to}}</p
					</div>
				</section>
				<section class="trip-page-section trip-user-info">
					<h3>Other users joining the trip</h3>
					{% for trip in trip_attendees %}
					<div class="data">
						<p class="attendee">{{trip.attendee.name}}</p>
					</div>
					{% endfor %}
				</section>
			</main>
		</div>
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="{% static 'login/js/materialize.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'login/js/app.js' %}"></script>
	</body>
</html>